#!/usr/bin/env python3
"""Observe report-summary behavior for a-stock-data financial fallback.

This script calls ``FinancialStatementsTool`` directly, forces the primary
provider to fail, and passes fallback ``_data_quality`` into the existing
report-summary helpers. It does not enter AgentLoop, start Web UI, or read
``agent/.env``.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from unittest.mock import patch


ROOT = Path(__file__).resolve().parents[1]
AGENT_DIR = ROOT / "agent"
if str(AGENT_DIR) not in sys.path:
    sys.path.insert(0, str(AGENT_DIR))

from src.adapters.a_stock_data.financials import fetch_a_stock_financials as live_fetch  # noqa: E402
from src.data_quality import (  # noqa: E402
    append_data_source_summary,
    append_no_estimate_warning,
    evaluate_market_data_report_gate,
    format_data_source_summary,
)
from src.tools.financial_statements_tool import FinancialStatementsTool  # noqa: E402


FORCED_PRIMARY_FAILURE = {
    "ok": False,
    "error": "forced_primary_failure_for_report_observation",
    "data": [],
}

PROMPT = "请分析 600519.SH 最近一期财务表现。只使用实际获取到的数据，不要估算。"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Observe report summary output for a-stock-data financial fallback."
    )
    parser.add_argument(
        "--symbols",
        default="600519.SH",
        help="Comma-separated explicit symbols. Default keeps this to one live request.",
    )
    parser.add_argument(
        "--statement-types",
        default="income",
        help="Comma-separated statement types: income,balance,cashflow.",
    )
    parser.add_argument("--timeout", type=float, default=15.0, help="Live fallback timeout seconds.")
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Optional ignored local directory for compact JSON summaries, e.g. local_reports.",
    )
    return parser.parse_args()


def _execute_tool(symbol: str, statement_type: str, *, timeout: float) -> dict[str, Any]:
    def _fetch_with_timeout(symbol_arg: str, statement_type: str | None = None, **kwargs: Any) -> dict[str, Any]:
        kwargs["timeout"] = timeout
        return live_fetch(symbol_arg, statement_type=statement_type, **kwargs)

    with patch.dict(os.environ, {"VIBE_TRADING_ENABLE_A_STOCK_DATA_ADAPTER": "1"}, clear=False):
        with patch(
            "src.tools.financial_statements_tool._fetch_eastmoney_statement",
            return_value=FORCED_PRIMARY_FAILURE,
        ):
            with patch("src.tools.financial_statements_tool.fetch_a_stock_financials", side_effect=_fetch_with_timeout):
                text = FinancialStatementsTool().execute(
                    code=symbol,
                    statement=statement_type,
                    period="annual",
                )
    return json.loads(text)


def _rows_for(result: dict[str, Any], symbol: str) -> list[Any]:
    data = result.get("data")
    if isinstance(data, dict):
        rows = data.get(symbol)
        if isinstance(rows, list):
            return rows
    return []


def _quality_for(result: dict[str, Any], symbol: str) -> dict[str, Any]:
    quality = result.get("_data_quality")
    if isinstance(quality, dict):
        value = quality.get(symbol)
        if isinstance(value, dict):
            return value
    return {}


def _section_present(text: str, heading: str) -> bool:
    return heading in (text or "")


def _extract_section(text: str, heading: str) -> str:
    if heading not in text:
        return ""
    start = text.index(heading)
    rest = text[start:]
    next_heading = rest.find("\n## ", len(heading))
    if next_heading == -1:
        return rest.strip()
    return rest[:next_heading].strip()


def observe_one(symbol: str, statement_type: str, *, timeout: float) -> dict[str, Any]:
    tool_result = _execute_tool(symbol, statement_type, timeout=timeout)
    rows = _rows_for(tool_result, symbol)
    quality = _quality_for(tool_result, symbol)
    data_quality = tool_result.get("_data_quality") if isinstance(tool_result.get("_data_quality"), dict) else {}

    base_report = (
        f"## Controlled Financial Fallback Observation\n\n"
        f"- Symbol: {symbol}\n"
        f"- Statement: {statement_type}\n"
        f"- Rows returned by tool: {len(rows)}\n"
        "- This synthetic report is generated by a script for structure observation only."
    )
    source_summary = format_data_source_summary(data_quality)
    report_with_summary = append_data_source_summary(base_report, data_quality)
    no_estimate_output = append_no_estimate_warning(report_with_summary, PROMPT)
    gate_decision = evaluate_market_data_report_gate(PROMPT, data_quality)

    warnings = quality.get("warnings") if isinstance(quality.get("warnings"), list) else []
    summary = {
        "tool_result_ok": tool_result.get("ok"),
        "symbol": symbol,
        "provider": tool_result.get("provider"),
        "source": tool_result.get("source"),
        "upstream": tool_result.get("upstream"),
        "statement_type": tool_result.get("statement_type") or tool_result.get("statement"),
        "row_count": len(rows),
        "latest_data_date": quality.get("latest_data_date"),
        "freshness_status": quality.get("freshness_status"),
        "warnings": warnings,
        "primary_error": quality.get("primary_error"),
        "source_summary_output": source_summary,
        "missing_data_output": _extract_section(source_summary, "## Missing Data"),
        "source_warnings_output": _extract_section(source_summary, "## Source Warnings"),
        "no_estimate_warning_output": _extract_section(no_estimate_output, "## No Estimate Warning"),
        "report_gate_decision": gate_decision,
        "compatibility": {
            "source_summary_has_a_stock_data": "a_stock_data" in source_summary,
            "source_summary_has_sina": "sina_financial_report" in source_summary,
            "warnings_include_primary_unavailable": "primary_financials_unavailable" in warnings,
            "warnings_include_fallback_used": "a_stock_data_fallback_used" in warnings,
            "no_false_realtime_claim_detected": not _section_present(no_estimate_output, "## No Estimate Warning"),
            "report_gate_does_not_block_valid_fallback": gate_decision.get("blocked") is False,
        },
    }
    return summary


def write_report(results: list[dict[str, Any]], output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(UTC).strftime("%Y%m%d_%H%M%S")
    path = output_dir / f"a_stock_financial_fallback_report_summary_observation_{timestamp}.json"
    payload = {
        "generated_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "script": "scripts/observe_a_stock_financial_fallback_report_summary.py",
        "forced_primary_failure": FORCED_PRIMARY_FAILURE,
        "prompt": PROMPT,
        "results": results,
    }
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return path


def main() -> int:
    args = parse_args()
    symbols = [item.strip().upper() for item in args.symbols.split(",") if item.strip()]
    statements = [item.strip().lower() for item in args.statement_types.split(",") if item.strip()]

    results: list[dict[str, Any]] = []
    for symbol in symbols:
        for statement_type in statements:
            summary = observe_one(symbol, statement_type, timeout=args.timeout)
            results.append(summary)
            print(
                "OK={ok} symbol={symbol} statement={statement} provider={provider} "
                "source={source} rows={rows} latest={latest} freshness={freshness}".format(
                    ok=summary["tool_result_ok"],
                    symbol=summary["symbol"],
                    statement=summary["statement_type"],
                    provider=summary["provider"],
                    source=summary["source"],
                    rows=summary["row_count"],
                    latest=summary["latest_data_date"],
                    freshness=summary["freshness_status"],
                )
            )
            print(f"warnings={summary['warnings']}")
            print(f"primary_error={summary['primary_error']}")
            print(f"compatibility={summary['compatibility']}")
            print("source_summary_excerpt=")
            print("\n".join(summary["source_summary_output"].splitlines()[:12]))
            print(f"missing_data_present={bool(summary['missing_data_output'])}")
            print(f"source_warnings_present={bool(summary['source_warnings_output'])}")
            print(f"no_estimate_warning_present={bool(summary['no_estimate_warning_output'])}")
            print(f"report_gate_blocked={summary['report_gate_decision'].get('blocked')}")
            print(f"report_gate_reason={summary['report_gate_decision'].get('reason')}")

    if args.output_dir:
        report_path = write_report(results, (ROOT / args.output_dir).resolve())
        print(f"JSON report: {report_path}")

    failed = [item for item in results if not all(item["compatibility"].values())]
    print(f"Summary: {len(results) - len(failed)}/{len(results)} compatible")
    return 0 if not failed else 1


if __name__ == "__main__":
    raise SystemExit(main())
